# Generated by Django 3.0.1 on 2019-12-31 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
