# Generated by Django 3.0.1 on 2019-12-31 10:04

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('projects', '0007_auto_20191231_1702'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='project',
            new_name='Projects',
        ),
    ]
