# Generated by Django 3.0.1 on 2019-12-29 04:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('contact', '0003_contactinfo_date_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='date_send',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True),
        ),
    ]
