# Generated by Django 3.0.1 on 2019-12-31 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, default='project_image/NO_IMAGE.jpg', height_field='height_field', null=True, upload_to='project_image', width_field='width_field')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
