# Generated by Django 3.0.1 on 2019-12-31 09:06

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('projects', '0003_auto_20191231_1603'),
    ]

    operations = [
        migrations.DeleteModel(
            name='project',
        ),
    ]
