# Generated by Django 3.0.1 on 2019-12-31 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('projects', '0005_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='media/project_image/NO_IMAGE.jpg', height_field='height_field', null=True, upload_to='media/project_image', width_field='width_field'),
        ),
    ]
