# Generated by Django 3.0.1 on 2019-12-31 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('projects', '0008_auto_20191231_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='image',
            field=models.ImageField(blank=True, default='image_request/NO_IMAGE.jpg', height_field='height_field', null=True, upload_to='image_request', width_field='width_field'),
        ),
        migrations.DeleteModel(
            name='ProjectImage',
        ),
    ]
