# Generated by Django 3.0.1 on 2019-12-31 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('projects', '0010_auto_20191231_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(default='project_image/NO_IMAGE.jpg', height_field='height_field', upload_to='project_image/', width_field='width_field'),
        ),
    ]
