# Generated by Django 3.0.1 on 2019-12-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('projects', '0011_auto_20191231_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='company',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='dev_team',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='duration',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='url',
            field=models.URLField(max_length=258, null=True),
        ),
    ]
