# Generated by Django 3.0.1 on 2020-01-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20191231_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='status',
            field=models.TextField(max_length=28, null=True),
        ),
    ]
